"""empty message

Revision ID: 1806d82dff35
Revises: 3a71f5e89d95
Create Date: 2018-11-04 13:36:20.874218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1806d82dff35'
down_revision = '3a71f5e89d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'role', ['display_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_column('role', 'display_name')
    # ### end Alembic commands ###
