"""empty message

Revision ID: 232431a22a03
Revises: f37b8ec3d36e
Create Date: 2019-03-06 16:54:52.587297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232431a22a03'
down_revision = 'f37b8ec3d36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('bucket', sa.String(), nullable=True))
    op.add_column('image', sa.Column('location', sa.String(), nullable=True))
    op.add_column('image', sa.Column('path', sa.Text(), nullable=True))
    op.drop_column('image', 'url')
    op.drop_column('image', 'cloudinary_public_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('cloudinary_public_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('image', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('image', 'path')
    op.drop_column('image', 'location')
    op.drop_column('image', 'bucket')
    # ### end Alembic commands ###
