"""empty message

Revision ID: 39a1143fa6c3
Revises: 7a6fd9bb966e
Create Date: 2018-10-25 02:14:17.301078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a1143fa6c3'
down_revision = '7a6fd9bb966e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('lastname', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
