"""empty message

Revision ID: afe7dc164211
Revises: 232431a22a03
Create Date: 2019-03-06 17:12:41.505431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe7dc164211'
down_revision = '232431a22a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('provider', sa.String(), nullable=True))
    op.drop_column('image', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('image', 'provider')
    # ### end Alembic commands ###
