"""empty message

Revision ID: cc896c6e090e
Revises: 4c59af5832ed
Create Date: 2019-03-08 19:23:11.818338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cc896c6e090e"
down_revision = "4c59af5832ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("primary_image_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "post", "image", ["primary_image_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "post", type_="foreignkey")
    op.drop_column("post", "primary_image_id")
    # ### end Alembic commands ###
