"""empty message

Revision ID: f37b8ec3d36e
Revises: 725a9836f2f2
Create Date: 2019-03-05 04:37:51.096749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f37b8ec3d36e"
down_revision = "725a9836f2f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("cloudinary_public_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "image_post",
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["image_id"], ["image.id"]),
        sa.ForeignKeyConstraint(["post_id"], ["post.id"]),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("image_post")
    op.drop_table("image")
    # ### end Alembic commands ###
