#!/usr/bin/env bash

COMPOSE=docker-compose
APP_CONTAINER=web
CELERY_CONTAINER=celery
CELERY_BEAT_CONTAINER=celery-beat

if [ $# -gt 0 ];then
    if [ "$1" == "cmd" ]; then
        shift 1
		$COMPOSE exec \
			$APP_CONTAINER \
			python manage.py "$@"
    elif [ "$1" == "celery" ]; then
        shift 1
		$COMPOSE exec \
			$APP_CONTAINER \
			celery "$@"
    elif [ "$1" == "terminal" ]; then
        shift 1
        $COMPOSE exec web /bin/sh
    else
        $COMPOSE "$@"
    fi
else
    $COMPOSE ps
fi