version: '3.0'
services:
  postgres:
    restart: always
    image: postgres:10
    env_file: app/app/.env
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=secret
    - POSTGRES_DB=blog
    volumes:
    - postgresdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  web:
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
