version: '3.0'
services:
  postgres:
    restart: always
    image: postgres:10
    volumes:
     - postgresdata:/var/lib/postgresql/data
    env_file: .docker_env
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=secret
    - POSTGRES_DB=blog
    ports:
    - "5432:5432"
    networks:
     - blognet
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - blognet
    ports:
     - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    environment:
    - RABBITMQ_DEFAULT_USER=queue
    - RABBITMQ_DEFAULT_PASS=secret
    - RABBITMQ_DEFAULT_VHOST=queue
    networks:
      - blognet
    ports:
      - "5672:5672"
      - "15672:15672"
  web:
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    networks:
      - blognet
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: /bin/bash /app/devstart.sh
volumes:
  postgresdata:
    driver: local
  redisdata:
      driver: local
networks:
  blognet:
    driver: "bridge"