version: '3.0'
services:
  postgres:
    restart: always
    image: postgres:10
    volumes:
     - postgresdata:/var/lib/postgresql/data
    env_file: .docker_env
    environment:
    - POSTGRES_USER=blog
    - POSTGRES_PASSWORD=secret
    - POSTGRES_DB=main
    ports:
    - "5432:5432"
    networks:
     - blognet
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - blognet
    ports:
     - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    environment:
    - RABBITMQ_DEFAULT_USER=tasks
    - RABBITMQ_DEFAULT_PASS=secret
    - RABBITMQ_DEFAULT_VHOST=tasks
    networks:
      - blognet
    ports:
      - "5672:5672"
      - "15672:15672"
  web:
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    networks:
      - blognet
    command: /bin/bash /app/devstart.sh
    depends_on:
      - postgres
      - redis
  celery-worker:
    build: ./
    restart: always
    volumes:
      - ./app:/app
    networks:
      - blognet
    environment:
    - FLASK_DEBUG=True
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "celery", "-A", "celery_worker.celery", "worker"]
    depends_on:
      - rabbitmq
volumes:
  postgresdata:
    driver: local
  redisdata:
      driver: local
networks:
  blognet:
    driver: "bridge"