version: '3.0'
services:
  postgres:
    restart: always
    image: postgres:10
    env_file: .docker_env
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=secretk
    - POSTGRES_DB=blog
    ports:
    - "5432:5432"
    networks:
     - blognet
  web:
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    networks:
      - blognet
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: /bin/bash /app/devstart.sh
#    command: flask run --host=0.0.0.0 --port=80
#      - /bin/bash /prestart.sh
#      -
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
