import os
from dotenv import load_dotenv

load_dotenv()


class Config:
    SECRET_KEY = os.getenv("SECRET_KEY")
    BLOG_TITLE = os.getenv("BLOG_TITLE")
    SERVER_NAME = os.getenv("SERVER_NAME")

    ADMIN_INIT_USERNAME = os.getenv("ADMIN_INIT_USERNAME")
    ADMIN_INIT_PASSWORD = os.getenv("ADMIN_INIT_PASSWORD")
    ADMIN_INIT_EMAIL = os.getenv("ADMIN_INIT_EMAIL")

    SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")

    CLOUD_FILE_PROVIDER = os.getenv("CLOUD_FILE_PROVIDER")
    CLOUDINARY_ON = os.getenv("CLOUDINARY_ON")
    CLOUDINARY_URL = os.getenv("CLOUDINARY_URL")
    CLOUDINARY_WIDTHS = os.getenv("CLOUDINARY_WIDTHS")

    UPLOAD_DIR = os.getenv("UPLOAD_DIR")
    UPLOAD_ALLOWED_EXTENSIONS = set(os.getenv("UPLOAD_ALLOWED_EXTENSIONS").split(","))

    REDIS_URL = os.getenv("REDIS_URL")
    REDIS_SESSION_PREFIX = os.getenv("REDIS_SESSION_PREFIX")

    CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
    CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")

    B2_KEY_ID = os.getenv("B2_KEY_ID")
    B2_APPLICATION_KEY = os.getenv("B2_APPLICATION_KEY")
    B2_BUCKET = os.getenv("B2_BUCKET")

    MAIL_DEFAULT_SENDER = os.getenv("MAIL_DEFAULT_SENDER")
    MAIL_SERVER = os.getenv("MAIL_SERVER")
    MAIL_PORT = os.getenv("MAIL_PORT")
    MAIL_USERNAME = os.getenv("MAIL_USERNAME")
    MAIL_PASSWORD = os.getenv("MAIL_PASSWORD")

    DEBUG_TB_INTERCEPT_REDIRECTS = False

    POST_SNIPPET_LENGTH = os.getenv("POST_SNIPPET_LENGTH")
    POSTS_PER_PAGE = os.getenv("POSTS_PER_PAGE")
    PAGINATE_DEFAULT = os.getenv("PAGINATE_DEFAULT")
